// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  // TODO(Phase 7): set the production URL once a deploy host is chosen.
  site: 'https://gears.dev',
  integrations: [
    starlight({
      title: 'Gears',
      description:
        'Documentation for Gears — a Rust runtime for composable, secure-by-default platform components.',
      logo: {
        src: './src/assets/gears-logo.svg',
        alt: 'Gears',
      },
      // Self-hosted variable fonts + the Gears theme tokens.
      customCss: [
        '@fontsource-variable/inter',
        '@fontsource-variable/space-grotesk',
        '@fontsource-variable/jetbrains-mono',
        './src/styles/theme.css',
      ],
      // Code blocks: a consistent graphite surface in both site modes, with a
      // restrained brass accent on the active tab / frame chrome.
      expressiveCode: {
        themes: ['github-dark'],
        styleOverrides: {
          borderRadius: '0.3rem',
          borderColor: '#2a2e34',
          codeBackground: '#1a1d21',
          frames: {
            editorActiveTabIndicatorTopColor: '#d8a657',
            editorActiveTabBackground: '#1d2024',
            editorTabBarBackground: '#15171a',
            terminalTitlebarBackground: '#15171a',
            terminalBackground: '#1a1d21',
          },
        },
      },
      // TODO(Phase 1): point at the real Gears source repository.
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/gears-rs/gears',
        },
      ],
      // Sidebar skeleton — the nine top-level sections from the IA.
      // Each section is autogenerated from its directory for now (Phase 1).
      // Explicit ordering/labels are tightened in Phase 3.
      sidebar: [
        {
          label: 'Introduction',
          items: [{ autogenerate: { directory: 'introduction' } }],
        },
        {
          label: 'Getting Started',
          items: [{ autogenerate: { directory: 'get-started' } }],
        },
        {
          label: 'Concepts',
          items: [{ autogenerate: { directory: 'concepts' } }],
        },
        {
          label: 'Guides',
          items: [{ autogenerate: { directory: 'guides' } }],
        },
        {
          label: 'Architecture',
          items: [{ autogenerate: { directory: 'architecture' } }],
        },
        {
          label: 'Reference',
          items: [{ autogenerate: { directory: 'reference' } }],
        },
        {
          label: 'Examples',
          items: [{ autogenerate: { directory: 'examples' } }],
        },
        {
          label: 'Contributing',
          items: [{ autogenerate: { directory: 'contributing' } }],
        },
      ],
    }),
  ],
});
