// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  // TODO(Phase 7): set the production URL once a deploy host is chosen.
  site: 'https://gears.dev',
  integrations: [
    starlight({
      title: 'Gears',
      description:
        'Documentation for Constructor Fabric Gears — a Rust runtime for composable, secure-by-default platform components.',
      logo: {
        src: './src/assets/gears-logo.svg',
        alt: 'Gears',
      },
      // Self-hosted variable fonts + the Gears theme tokens.
      customCss: [
        '@fontsource-variable/inter',
        '@fontsource-variable/jetbrains-mono',
        './src/styles/theme.css',
      ],
      // Code blocks: a consistent graphite surface in both site modes, with a
      // restrained brass accent on the active tab / frame chrome.
      // Code blocks: a consistent graphite surface in both site modes, with the
      // brand-blue accent on the active tab. Values mirror the --gears-code-*
      // tokens in theme.css (Expressive Code overrides cannot read CSS variables).
      expressiveCode: {
        themes: ['github-dark'],
        styleOverrides: {
          borderRadius: '0.5rem',
          borderWidth: '1px',
          // A clearly visible cool border + a code surface lifted above the page
          // background so the block reads as a distinct panel (the page bg is
          // #0f1217). Values mirror the --gears-code-* tokens in theme.css.
          borderColor: '#2d3a47',
          codeBackground: '#1a2029',
          frames: {
            editorActiveTabIndicatorTopColor: '#4f9fe0',
            editorActiveTabBackground: '#1a2029',
            editorTabBarBackground: '#12161c',
            terminalTitlebarBackground: '#12161c',
            terminalBackground: '#1a2029',
          },
        },
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/constructorfabric/gears-rust',
        },
      ],
      // Sidebar skeleton — the nine top-level sections from the IA.
      // Each section is autogenerated from its directory for now (Phase 1).
      // Explicit ordering/labels are tightened in Phase 3.
      sidebar: [
        {
          label: 'Introduction',
          items: [{ autogenerate: { directory: 'introduction' } }],
        },
        {
          label: 'Getting Started',
          items: [{ autogenerate: { directory: 'get-started' } }],
        },
        {
          label: 'Concepts',
          items: [{ autogenerate: { directory: 'concepts' } }],
        },
        {
          label: 'Guides',
          items: [{ autogenerate: { directory: 'guides' } }],
        },
        {
          label: 'Architecture',
          items: [{ autogenerate: { directory: 'architecture' } }],
        },
        {
          label: 'Reference',
          items: [{ autogenerate: { directory: 'reference' } }],
        },
        {
          label: 'Examples',
          items: [{ autogenerate: { directory: 'examples' } }],
        },
        {
          label: 'Contributing',
          items: [{ autogenerate: { directory: 'contributing' } }],
        },
      ],
    }),
  ],
});
