// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// GitHub Pages URL: https://constructorfabric.github.io/gears-rust-web-docs
// Content links are authored relative (../guides/...) in gears-rust, so they
// resolve correctly under this base path and would also work at a root custom
// domain. For a custom domain (gears.dev) drop `base` and set site accordingly.
const BASE = process.env.BASE ?? '/gears-rust-web-docs';

// https://astro.build/config
export default defineConfig({
  site: 'https://constructorfabric.github.io',
  base: BASE,
  // Emit all stylesheets as files (don't inline small ones). Avoids an
  // Expressive Code asset-hash mismatch on pages whose code blocks are all
  // plaintext, which otherwise produced a 404 link to an un-emitted CSS file.
  build: { inlineStylesheets: 'never' },
  integrations: [
    starlight({
      title: 'Gears',
      description:
        'Documentation for Constructor Fabric Gears — a Rust runtime for composable, secure-by-default platform components.',
      // `root` keeps English at `/` (no `/en/` prefix). i18n can be enabled
      // later by adding locales here and a matching src/content/docs/<lang>/ dir.
      defaultLocale: 'root',
      locales: {
        root: { label: 'English', lang: 'en' },
      },
      // "Edit page" links point at the source in gears-rust, not this docs repo.
      // Users edit in the source repo (docs/web-docs/), then sync handles the update.
      editLink: {
        baseUrl: 'https://github.com/constructorfabric/gears-rust/edit/main/docs/web-docs/',
      },
      logo: {
        src: './src/assets/gears-logo.svg',
        alt: 'Gears',
      },
      // Self-hosted variable fonts + the Gears theme tokens.
      customCss: [
        '@fontsource-variable/inter',
        '@fontsource-variable/jetbrains-mono',
        './src/styles/theme.css',
      ],
      // Code blocks: a consistent graphite surface in both site modes, with a
      // restrained brass accent on the active tab / frame chrome.
      // Code blocks: a consistent graphite surface in both site modes, with the
      // brand-blue accent on the active tab. Values mirror the --gears-code-*
      // tokens in theme.css (Expressive Code overrides cannot read CSS variables).
      expressiveCode: {
        themes: ['github-dark'],
        styleOverrides: {
          borderRadius: '0.5rem',
          borderWidth: '1px',
          // A clearly visible cool border + a code surface lifted above the page
          // background so the block reads as a distinct panel (the page bg is
          // #0f1217). Values mirror the --gears-code-* tokens in theme.css.
          borderColor: '#2d3a47',
          codeBackground: '#1a2029',
          frames: {
            editorActiveTabIndicatorTopColor: '#4f9fe0',
            editorActiveTabBackground: '#1a2029',
            editorTabBarBackground: '#12161c',
            terminalTitlebarBackground: '#12161c',
            terminalBackground: '#1a2029',
          },
        },
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/constructorfabric/gears-rust',
        },
      ],
      // Sidebar skeleton — the nine top-level sections from the IA.
      // Each section is autogenerated from its directory for now (Phase 1).
      // Explicit ordering/labels are tightened in Phase 3.
      sidebar: [
        {
          label: 'Introduction',
          items: [{ autogenerate: { directory: 'introduction' } }],
        },
        {
          label: 'Getting Started',
          items: [{ autogenerate: { directory: 'get-started' } }],
        },
        {
          label: 'CLI',
          items: [{ autogenerate: { directory: 'cli' } }],
        },
        {
          label: 'Concepts',
          items: [{ autogenerate: { directory: 'concepts' } }],
        },
        {
          label: 'Guides',
          items: [{ autogenerate: { directory: 'guides' } }],
        },
        {
          label: 'Architecture',
          items: [{ autogenerate: { directory: 'architecture' } }],
        },
        {
          label: 'Reference',
          items: [{ autogenerate: { directory: 'reference' } }],
        },
        {
          label: 'Examples',
          items: [{ autogenerate: { directory: 'examples' } }],
        },
        {
          label: 'Contributing',
          items: [{ autogenerate: { directory: 'contributing' } }],
        },
      ],
    }),
  ],
});
